#!/bin/bash

# Copyright (C) 2022 Antmicro
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

if [[ -z "$FPGA_INTERCHANGE_TESTS_PATH" ]]; then
    FPGA_INTERCHANGE_TESTS_PATH="fpga-interchange-tests"
fi

if [[ -z "$DEVICE" ]]; then
    DEVICE=xczu7ev
fi

if [[ "$DEBUG_MODE" = 1 ]]; then
    DEVICE_PATH="${FPGA_INTERCHANGE_TESTS_PATH}/build/devices/${DEVICE}/${DEVICE}.device.raw"
else
    DEVICE_PATH="${FPGA_INTERCHANGE_TESTS_PATH}/build/devices/${DEVICE}/${DEVICE}.device"
fi

if [[ -z "$LOG" ]]; then
    LOG=nisp.log
fi

BBA=test_out/${DEVICE}_extra.bba

EXTRA_OPTS=$EXTRA_OPTS
BIN_PATH=""

export FPGA_INTERCHANGE_SCHEMA_DIR="${FPGA_INTERCHANGE_TESTS_PATH}/third_party/fpga-interchange-schema"
if [[ "$DEBUG_MODE" = 1 ]]; then
    cargo build
    EXTRA_OPTS="${EXTRA_OPTS} --raw"
    BIN_PATH="./target/debug/nisp"
else
    cargo build --release
    BIN_PATH="./target/release/nisp"
fi

if [[ -n "$TILE_TYPES" ]]; then
    EXTRA_OPTS="${EXTRA_OPTS} --tile-types ${TILE_TYPES}"
fi

if [[ -n "$THREADS" ]]; then
    EXTRA_OPTS="${EXTRA_OPTS} --threads ${THREADS}"
fi

echo "Running \`$BIN_PATH $DEVICE_PATH $BBA $EXTRA_OPTS\`"
echo ""
export RUST_BACKTRACE=1
$BIN_PATH $DEVICE_PATH $BBA $EXTRA_OPTS 2>&1 | tee $LOG
